version: '2'

services:
    zookeeper:
        image: hyperledger/fabric-zookeeper:x86_64-1.0.6-snapshot-c23f6cc
        ports:
            - "2181:2181"
    kafka:
        image: hyperledger/fabric-kafka:x86_64-1.0.6-snapshot-c23f6cc
        restart: always
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_ADVERTISED_PORT=9092
            - KAFKA_BROKER_ID=0
            - KAFKA_MESSAGE_MAX_BYTES=103809024 
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_NUM_REPLICA_FETCHERS=1
            - KAFKA_DEFAULT_REPLICATION_FACTOR=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper


